# Generated by Django 6.1.1 on 2026-09-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_truckstop_id', models.BigIntegerField(db_index=True)),
                ('truckstop_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('rack_id', models.IntegerField()),
                ('retail_price', models.DecimalField(db_index=True, decimal_places=8, max_digits=12)),
                ('source_fingerprint', models.CharField(editable=False, max_length=64, unique=True)),
                ('latitude', models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True)),
                ('geocoded_country_code', models.CharField(blank=True, max_length=2)),
            ],
            options={
                'ordering': ('retail_price', 'opis_truckstop_id'),
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='station_lat_lon_idx'), models.Index(fields=['state', 'city'], name='station_state_city_idx')],
            },
        ),
    ]
