# Generated by Django 6.1.1 on 2026-09-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstation',
            name='location_precision',
            field=models.CharField(default='city', max_length=8),
        ),
    ]
